name: CI for Group Projects

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  react-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Up Node for Frontend
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - run: npm ci
      working-directory: ./frontend
    - run: npm run build --if-present
      working-directory: ./frontend
    - run: npm test
      working-directory: ./frontend